{{- if .Values.management.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "zergling.fullname" . }}-management
  labels:
    django-component: manager
    {{ include "zergling.labels" . | nindent 4 }}
spec:
  template:
    metadata:
      labels:
        django-component: manager
        {{ include "zergling.labels" . | nindent 8 }}
    spec:
      restartPolicy: OnFailure
      containers:
      - name: db-migrator
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command:
          - /bin/sh
          - -c
          - |
            set -x;
            python manage.py makemigrations zergling;
            python manage.py migrate zergling;
        env:
          {{ include "zergling.plugins" . | nindent 10 }}

        {{- if .Values.envFromSecret.enabled }}
        envFrom:
          - secretRef:
              name: {{ .Values.envFromSecret.name | default (include "zergling.name" .) }}
        {{- end }}
        resources:
          {{ toYaml .Values.management.resources | nindent 10 }}

---
{{- end }}

apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "zergling.fullname" . }}-cleanup
  labels:
    {{ include "zergling.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-upgrade"
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": "hook-succeeded"
spec:
  template:
    metadata:
      labels:
        {{ include "zergling.labels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      containers:
      - name: job-cleanup
        image: {{ .Values.cleanup.image.repository }}:{{ .Values.cleanup.image.tag }}
        imagePullPolicy: {{ .Values.cleanup.image.pullPolicy }}
        command:
          - /bin/sh
          - -c
          - |
            kubectl delete jobs --namespace {{ .Release.Namespace }} \
              --selector=django-component=manager
            kubectl delete pods --namespace {{ .Release.Namespace }} \
              --field-selector='status.phase!=Running' \
              --selector='django-component=celery-tasks'
            kubectl delete pods --namespace {{ .Release.Namespace }} \
              --field-selector='status.phase=Succeeded' \
              --selector='django-component=manager'
        resources:
          {{ toYaml .Values.cleanup.resources | nindent 10 }}
