apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ include "rehive-service.fullname" . }}
  labels:
    {{ include "rehive-service.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ include "rehive-service.name" . }}
    app.kubernetes.io/component: webserver
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "rehive-service.name" . }}
      app.kubernetes.io/component: webserver
      app: webapp
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      annotations:
        helm/revision: "{{ .Release.Revision }}" # Hack to force restart on upgrade
      labels:
        app.kubernetes.io/name: {{ include "rehive-service.name" . }}
        app.kubernetes.io/component: webserver
        app: webapp
    spec:
      containers:
      - name: webapp
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.internalPort }}
        command:
          {{- toYaml .Values.deployment.command | nindent 12 }}
        args:
          {{- range $key, $value := .Values.deployment.args }}
          {{- if $value }}
          - --{{ $key }}={{ $value }}
          {{- else }}
          - --{{ $key }}
          {{- end }}
          {{- end }}
        env:
        {{- if .Values.gcloudCredentials.enabled }}
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: "/etc/credentials/{{ .Values.gcloudCredentials.kubernetesSecret }}.json"
        {{- end }}
          {{ include "rehive-service.plugins" . | nindent 10 }}
        {{- if .Values.envFromSecret.enabled }}
        envFrom:
          - secretRef:
              name: {{ .Values.envFromSecret.name | default (include "rehive-service.fullname" .) }}
        {{- end }}
        {{- with .Values.service.livenessProbe }}
        livenessProbe:
          {{ toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.service.readinessProbe }}
        readinessProbe:
          {{ toYaml . | nindent 10 }}
        {{- end}}
        resources:
          {{ toYaml .Values.deployment.resources | nindent 10 }}
        {{- if .Values.gcloudCredentials.enabled }}
        volumeMounts:
          - name: {{ .Values.gcloudCredentials.kubernetesSecret }}
            mountPath: /etc/credentials
            readOnly: true
        {{- end }}
      {{- if (eq "azure" .Values.vendor.name) }}
      dnsConfig:
        options:
        - name: single-request-reopen
      {{- end }}
      {{- if .Values.gcloudCredentials.enabled }}
      volumes:
        - name: {{ .Values.gcloudCredentials.kubernetesSecret }}
          secret:
            secretName: {{ .Values.gcloudCredentials.kubernetesSecret }}
      {{- end }}