{{- if .Values.ingress.enabled -}}
{{- $serviceName := include "rehive-service.fullname" . -}}
{{- $servicePort := .Values.service.externalPort -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "rehive-service.fullname" . }}
  labels:
    {{ include "rehive-service.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ include "rehive-service.name" . }}
    app.kubernetes.io/component: ingress-service
  {{- with .Values.ingress.annotations }}
  annotations:
    {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
    {{- range $host := .Values.ingress.hosts }}
    - host: {{ $host }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ $serviceName }}
              servicePort: {{ $servicePort }}
    {{- end -}}
  {{- with .Values.ingress.tls }}
  tls:
    {{ toYaml . | nindent 4 }}
  {{- end -}}
{{- end -}}
