{{- if .Values.ingress.enabled -}}
{{- $serviceName := include "rehive-service.fullname" . -}}
{{- $servicePort := .Values.service.externalPort -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "rehive-service.fullname" . }}
  labels:
    {{ include "rehive-service.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ include "rehive-service.fullname" . }}
    app.kubernetes.io/component: ingress
  {{- with .Values.ingress.annotations }}
  annotations:
    {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
    {{- range $host := .Values.ingress.hosts }}
    - host: {{ $host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $serviceName }}
                port:
                  number: {{ $servicePort }}
    {{- end -}}
  {{- with .Values.ingress.tls }}
  tls:
    {{ toYaml . | nindent 4 }}
  {{- end -}}
{{- end -}}
