{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "rehive-service.fullname" . }}
  labels:
    {{ include "rehive-service.labels" . | nindent 4 }}
{{- with .Values.rbac.rules }}
rules:
  {{ toYaml . | nindent 10 }}
{{- end }}
{{- end }}
