apiVersion: v1
kind: Service
metadata:
  name: {{ include "rehive-service.fullname" . }}
  labels:
    {{ include "rehive-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
      protocol: TCP
      name: {{ .Values.service.name }}
  selector:
    app.kubernetes.io/name: {{ include "rehive-service.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
