{{- $labels := include "rehive-service.labels" . }}
{{- $plugins := include "rehive-service.plugins" . }}
{{- $serviceName := include "rehive-service.fullname" . }}
{{- $serviceAccountName := include "rehive-service.serviceAccountName" . }}
{{- $gcloudCredentials := .Values.gcloudCredentials }}
{{- $envFromSecret := .Values.envFromSecret }}
{{- $podSecurityContext := .Values.podSecurityContext }}
{{- $containerSecurityContext := .Values.containerSecurityContext }}
{{- $releaseName := .Release.Name }}
{{- $repository := .Values.image.repository }}
{{- $revision := .Release.Revision }}
{{- $tag := .Values.image.tag }}
{{- $vendorName := .Values.vendor.name }}
{{- $imagePullSecret := .Values.imagePullSecrets | default dict }}
{{- if .Values.workers.enabled }}
{{- range $worker := .Values.workers.deployments }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $worker.name }}
  labels:
    {{ $labels | nindent 4 }}
    app.kubernetes.io/name: {{ $serviceName }}
    app.kubernetes.io/component: worker
    rehive.io/worker: {{ $worker.name }}
spec:
  replicas: {{ $worker.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $serviceName }}
      app.kubernetes.io/component: worker
      rehive.io/worker: {{ $worker.name }}
  strategy:
    {{- if $worker.strategy }}
    {{- toYaml $worker.strategy | nindent 4 }}
    {{- else }}
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 2
    {{- end }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ $serviceName }}
        app.kubernetes.io/component: worker
        rehive.io/worker: {{ $worker.name }}
      annotations:
        helm/revision: "{{ $revision }}" # Hack to force restart on upgrade
    spec:
      serviceAccountName: {{ $serviceAccountName }}
      {{- with $worker.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $worker.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: {{ $worker.terminationGracePeriodSeconds | default 60 }}
      {{- with $worker.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ $worker.name }}
        image: {{ $repository }}:{{ $tag }}
        imagePullPolicy: {{ $.Values.image.pullPolicy }}
        {{- with $containerSecurityContext }}
        securityContext:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with $worker.internalPort }}
        ports:
        - containerPort: {{ . }}
        {{- end }}
        command:
          {{- toYaml $worker.command | nindent 12 }}
        args:
          {{- range $key, $value := $worker.args }}
          {{- if $value }}
          - --{{ $key }}={{ $value }}
          {{- else }}
          - --{{ $key }}
          {{- end }}
          {{- end }}
        {{- with $worker.lifecycle }}
        lifecycle:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        env:
        {{- if $gcloudCredentials.enabled }}
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: "/etc/credentials/{{ $gcloudCredentials.kubernetesSecret }}.json"
        {{- end }}
          - name: VERSION
            value: "{{ $tag }}"
          {{ $plugins | nindent 10 }}
        {{- if $envFromSecret.enabled }}
        envFrom:
          - secretRef:
              name: {{ $envFromSecret.name | default $serviceName }}
        {{- end }}
        resources:
          {{ toYaml $worker.resources | nindent 10 }}
        {{- if $gcloudCredentials.enabled }}
        volumeMounts:
          - name: {{ $gcloudCredentials.kubernetesSecret }}
            mountPath: /etc/credentials
            readOnly: true
        {{- end }}
      {{- if (eq "azure" $vendorName) }}
      dnsConfig:
        options:
          - name: single-request-reopen
      {{- end }}
      {{- if $gcloudCredentials.enabled }}
      volumes:
        - name: {{ $gcloudCredentials.kubernetesSecret }}
          secret:
            secretName: {{ $gcloudCredentials.kubernetesSecret }}
      {{- end }}
      {{- if $imagePullSecret.name}}
      imagePullSecrets:
      - name: {{ $imagePullSecret.name}}
      {{- end }}
{{- end }}
{{- end }}
