apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: autosnap-backup
  labels:
    name: backup
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: backup
    spec:
      containers:
        - name: backup
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          env:
            - name: PROJECT
              value: {{ .Values.project }}
            - name: DISK
              value: {{ .Values.disk }}
            - name: ZONE
              value: {{ .Values.zone }}
            - name: SNAPSHOT_NAME
              value: {{ .Values.snapshotName }}
            - name: INTERVAL_MINUTES
              value: "{{ .Values.interval }}"
          command: ['/bin/bash','-c','python app.py']
          resources:
{{ toYaml .Values.resources | indent 12 }}