# Default values for zergling.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
environment: staging

envFromSecret:
  enabled: true
  name: zergling-gitbot

webapp:
  command:
    - gunicorn
  args:
    - run:app
    - --config
    - file:config/gunicorn.py

image:
  repository: gcr.io/rehive-services/zergling-gitbot
  tag: latest
  pullPolicy: IfNotPresent

service:
  name: nginx
  type: ClusterIP
  externalPort: 80
  internalPort: 8000

ingress:
  enabled: true
  hosts:
    - zergling-gitbot.s.services.rehive.io
  annotations:
    kubernetes.io/ingress.class: "nginx"
    kubernetes.io/tls-acme: "true"
  tls:
    - hosts:
      - zergling-gitbot.s.services.rehive.io
      secretName: zergling-gitbot-tls

cleanup:
  image:
    repository: gcr.io/google-containers/hyperkube
    tag: v1.13.7
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 266m
      memory: 512Mi
    requests:
      cpu: 266m
      memory: 128Mi

continuousDeployments:
  enabled: false
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
  repositories:
    - user: rehive
      name: docs-portal
      image: gcr.io/rehive-services/zergling-repository
      tag: 3c9ead9

management:
  enabled: true
  resources:
    limits:
      cpu: 266m
      memory: 512Mi
    requests:
      cpu: 266m
      memory: 128Mi

postgres:
  enabled: false
  host: localhost
  port: 5432
  user: postgres
  secret:
    key: postgres-password
    name: postgres-zergling-gitbot

rabbitmq:
  enabled: false
  host: localhost
  port: 5672
  user: rabbit
  secret:
    name: rabbitmq-zergling-gitbot
    key: rabbitmq-password

resources:
  limits:
    cpu: 200m
    memory: 600Mi
  requests:
    cpu: 100m
    memory: 200Mi

nodeSelector: {}

tolerations: []

affinity: {}
