apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      annotations:
        helm/revision: "{{ .Release.Revision }}" # Hack to force restart on upgrade
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.internalPort }}
        command:
          {{ toYaml .Values.deployment.command | nindent 10 }}
        env:
          {{ toYaml .Values.env | nindent 10 }}
        envFrom:
          {{ toYaml .Values.envFrom | nindent 10 }}
        {{- if .Values.service.livenessProbe }}
        livenessProbe:
          {{ toYaml .Values.service.livenessProbe | nindent 10 }}
        {{- end }}
        {{- if .Values.service.readinessProbe }}
        readinessProbe:
          {{ toYaml .Values.service.readinessProbe | nindent 10 }}
        {{- end}}
        resources:
          {{ toYaml .Values.deployment.resources | nindent 10 }}
        volumeMounts:
          {{ toYaml .Values.volumeMounts | nindent 10 }}
    volumes:
      {{ toYaml .Values.volumes | nindent 8 }}
---
{{- if .Values.management.enabled }}
apiVersion: v1
kind: Pod
metadata:
  name: "{{ template "fullname" . }}-management"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
  annotations:
    helm/revision: "{{ .Release.Revision }}" # Hack to force restart on upgrade
spec:
  containers:
  - name: management
    image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
    imagePullPolicy: {{ .Values.image.pullPolicy }}
    command: ['/bin/sh','-c', 'python manage.py runserver'] # Hack to create long-running pod
    env:
      {{ toYaml .Values.env | nindent 10 }}
    envFrom:
      {{ toYaml .Values.envFrom | nindent 10 }}
    resources:
      {{ toYaml .Values.deployment.management.resources | nindent 10 }}
    volumeMounts:
      {{ toYaml .Values.volumeMounts | nindent 10 }}
  volumes:
    {{ toYaml .Values.volumes | nindent 8 }}
{{- end }}
