apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      annotations:
        helm/revision: "{{ .Release.Revision }}" # Hack to force restart on upgrade
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.internalPort }}
        command: {{ .Values.deployment.command }}
        env:
{{ toYaml .Values.deployment.env | indent 10 }}
{{- if .Values.service.livenessProbe }}
        livenessProbe:
{{ toYaml .Values.service.livenessProbe | indent 10 }}
{{- end }}
{{- if .Values.service.readinessProbe }}
        readinessProbe:
{{ toYaml .Values.service.readinessProbe | indent 10 }}
{{- end}}
        resources:
{{ toYaml .Values.deployment.resources | indent 10 }}
---
{{- if .Values.management.enabled }}
apiVersion: v1
kind: Pod
metadata:
  name: "{{ template "fullname" . }}-management"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
  annotations:
    helm/revision: "{{ .Release.Revision }}" # Hack to force restart on upgrade
spec:
  containers:
  - name: management
    image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
    imagePullPolicy: {{ .Values.image.pullPolicy }}
    command: ['/bin/sh','-c', 'python manage.py runserver'] # Hack to create long-running pod
    env:
{{ toYaml .Values.deployment.env | indent 10 }}
{{ toYaml .Values.deployment.management.resources | indent 10 }}
{{- end }}
