{{- $replicaCount := .Values.deployment.replicaCount -}}
{{- $repository := .Values.image.repository -}}
{{- $env := .Values.env -}}
{{- $envFrom := .Values.envFrom -}}
{{- $tag := .Values.image.tag -}}
{{- $serviceName := include "fullname" . -}}
{{- $revision := .Release.Revision -}}

{{- if .Values.workers.enabled -}}
{{- range $worker := .Values.workers.deployments }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ $worker.name }}
spec:
  replicas: {{ $worker.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 2
  template:
    metadata:
      labels:
        app: {{ $worker.name }}
      annotations:
        helm/revision: "{{ $revision }}" # Hack to force restart on upgrade
    spec:
      containers:
      - name: {{ $worker.name }}
        image: "{{ $repository }}:{{ $tag }}"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: {{ $worker.internalPort }}
        command: {{ $worker.command }}
        env:
          {{ toYaml $env | indent 10 }}
        envFrom:
          {{ toYaml $envFrom | nindent 10 }}
        resources:
          {{ toYaml $worker.resources | nindent 10 }}
        volumeMounts:
          {{ toYaml $worker.volumeMounts | nindent 10 }}
    volumes:
      {{ toYaml $worker.volumes | nindent 8 }}
---
{{ end }}
{{- end -}}
