apiVersion: v1
kind: Service
metadata:
  name: {{ template "bitcoin-core.fullname" . }}
  labels:
    app: {{ template "bitcoin-core.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    application: {{ template "bitcoin-core.name" . }}
    cluster: {{ template "bitcoin-core.fullname" . }}
spec:
  type: ClusterIP
  ports:
    - name: rpc
      port: {{ .Values.service.rpcPort }}
      targetPort: rpc
    - name: p2p
      port: {{ .Values.service.p2pPort }}
      targetPort: p2p
    - name: testnet
      port: {{ .Values.service.testnetPort }}
    - name: testnet-p2p
      port: {{ .Values.service.testnetP2pPort }}