# Default values for rehive-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image: 
  repository: rehive/autosnap
  tag: 0.0.3
snapshotName: example
project: gcloud-example
disk: my-disk
zone: europe-west1-c
interval: 10
resources:
  requests:
    memory: 256Mi
    cpu: 100m
  limits:
    memory: 256Mi
    cpu: 100m