apiVersion: v1
kind: Secret
metadata:
  name: {{ template "patroni.fullname" . }}
  labels:
    app: {{ template "patroni.name" . }}
    chart: {{ template "patroni.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    cluster: {{ template "patroni.fullname" . }}
type: Opaque
stringData:
  {{ if .Release.IsInstall }}
  password-admin: {{ randAlphaNum 10 | quote }}
  password-standby: {{ randAlphaNum 10 | quote }}
  password-superuser: {{ randAlphaNum 10 | quote }}
  {{ end }}