apiVersion: v1
kind: Secret
metadata:
  name: {{ template "patroni.fullname" . }}
  labels:
    app: {{ template "patroni.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    application: {{ template "patroni.name" . }}
    cluster: {{ template "patroni.fullname" . }}
type: Opaque
data:
  {{ if .Values.credentials.superuser }}
  password-superuser: {{ .Values.credentials.superuser | b64enc }}
  {{ else }}
  password-superuser: {{ randAlphaNum 10 | b64enc | quote }}
  {{ end }}
  {{ if .Values.credentials.admin }}
  password-admin: {{ .Values.credentials.admin | b64enc }}
  {{ else }}
  password-admin: {{ randAlphaNum 10 | b64enc | quote }}
  {{ end }}
  {{ if .Values.credentials.standby }}
  password-standby: {{ .Values.credentials.standby | b64enc }}
  {{ else }}
  password-standby: {{ randAlphaNum 10 | b64enc | quote }}
  {{ end }}