apiVersion: v1
kind: Service
metadata:
  name: {{ template "patroni.fullname" . }}
  labels:
    app: {{ template "patroni.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    application: {{ template "patroni.name" . }}
    cluster: {{ template "patroni.fullname" . }}
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: postgresql
      name: postgresql
      protocol: TCP
