{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "patroni.serviceAccountName" . }}
  labels:
    app: {{ template "patroni.name" . }}
    chart: {{ template "patroni.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "patroni.serviceAccountName" . }}-cleanup
  labels:
    app: {{ template "patroni.name" . }}
    chart: {{ template "patroni.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-weight": "-4"
    "helm.sh/hook-delete-policy": hook-succeeded
{{- end }}
