apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "patroni.fullname" . }}
  labels:
    app: {{ template "patroni.name" . }}
    chart: {{ template "patroni.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    application: {{ template "patroni.name" . }}
    cluster: {{ template "patroni.fullname" . }}
spec:
  serviceName: {{ template "patroni.fullname" . }}
  replicas: {{ .Values.replicas }}
  updateStrategy:
    type: OnDelete
  selector:
    matchLabels:
      app: {{ template "patroni.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "patroni.name" . }}
        release: {{ .Release.Name }}
        application: {{ template "patroni.name" . }}
        cluster: {{ template "patroni.fullname" . }}
    spec:
      serviceAccountName: {{ template "patroni.serviceAccountName" . }}
      containers:
        - name: spilo
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.image.init }}
          command:
            - '/bin/sh'
          args:
            - '/launch.sh'
            - init
          {{- else }}
          command:
            {{- toYaml .Values.image.command | nindent 12 }}
          args:
            {{- toYaml .Values.image.args | nindent 12 }}
          {{- end}}
          env:
            - name: DEBUG
              value: {{ .Values.debug | quote }}
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: POD_NAMESPACE
              value: {{ .Release.Namespace }}
            - name: DCS_ENABLE_KUBERNETES_API
              value: "true"
            - name: USE_KUBERNETES
              value: "true"
            {{- if .Values.useConfigMaps }}
            - name: KUBERNETES_USE_CONFIGMAPS
              value: "true"
            {{- end }}
            - name: PATRONI_CONFIGURATION_FILE
              value: /etc/patronictl/patronictl.yaml
            - name: SCOPE
              value: {{ template "patroni.fullname" . }}
            - name: PGPASSWORD_SUPERUSER
              valueFrom:
                secretKeyRef:
                  name: {{ template "patroni.fullname" . }}
                  key: password-superuser
            - name: PGPASSWORD_ADMIN
              valueFrom:
                secretKeyRef:
                  name: {{ template "patroni.fullname" . }}
                  key: password-admin
            - name: PGPASSWORD_STANDBY
              valueFrom:
                secretKeyRef:
                  name: {{ template "patroni.fullname" . }}
                  key: password-standby
            - name: PGROOT
              value: /home/postgres/pgdata

            {{ if .Values.backup.enabled }}
            {{ if .Values.backup.scheduleCronJob }}
            - name: BACKUP_SCHEDULE
              value: {{ .Values.backup.scheduleCronJob | quote }}
            {{ end }}
            {{ if .Values.backup.retainBackups }}
            - name: BACKUP_NUM_TO_RETAIN
              value: {{ .Values.backup.retainBackups | quote }}
            {{ end }}
            {{ if .Values.backup.gsBucket }}
            - name: WAL_GS_BUCKET
              value: {{ .Values.backup.gsBucket | quote }}
            {{ end }}
            {{ if eq .Values.backup.method.name "wal-e" }}
            {{ with .Values.backup.method.wal_e }}
              ### TODO add more wal-e settings for gs
            - name: WALE_BACKUP_THRESHOLD_MEGABYTES
              value: {{ .backupThresholdMegabytes | quote }}
            - name: WALE_BACKUP_THRESHOLD_PERCENTAGE
              value: {{ .backupThresholdPercentage | quote }}
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/etc/credentials/{{ .gcloudCredentials }}"
            {{ end }}
            {{ else if eq .Values.backup.method.name "wal-g" }}
            {{ with .Values.backup.method.wal_g }}
              ### TODO add more wal-g settings for gs
            - name: USE_WALG
              value: "true"
            - name: USE_WALG_BACKUP
              value: "true"
            - name: WALG_BACKUP_COMPRESSION_METHOD
              value: {{ .backupCompressionMethod | quote }}
            - name: WALG_COMPRESSION_METHOD
              value: {{ .compressionMethod | quote }}
            - name: WALG_DELTA_MAX_STEPS
              value: {{ .deltaMaxSteps | quote }}
            - name: WALG_DELTA_ORIGIN
              value: {{ .deltaOrigin | quote }}
            - name: WALG_DISK_RATE_LIMIT
              value: {{ .diskRateLimit | quote }}
            - name: WALG_DOWNLOAD_CONCURRENCY
              value: {{ .downloadConcurrency | quote }}
            - name: WALG_NETWORK_RATE_LIMIT
              value: {{ .networkRateLimit | quote }}
            - name: WALG_PREVENT_WAL_OVERWRITE
              value: {{ .preventWalOverwrite | quote }}
            - name: WALG_UPLOAD_CONCURRENCY
              value: {{ .uploadConcurrency | quote }}
            - name: WALG_UPLOAD_DISK_CONCURRENCY
              value: {{ .uploadDiskConcurrency | quote }}
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/etc/credentials/{{ .gcloudCredentials }}"
            {{ end }}
            {{ end }}
            {{ end }}

            {{ if .Values.restore.enabled }}
            - name: CLONE_WAL_GS_BUCKET
              value: {{ .Values.restore.gsBucket | quote }}
            - name: CLONE_SCOPE
              value: {{ .Values.restore.scope | quote }}
            - name: CLONE_METHOD
              value: "CLONE_WITH_WALE"
            - name: CLONE_TARGET_TIME
              value: {{ .Values.restore.targetTime | quote }}
            {{ if eq .Values.restore.method.name "wal-g" }}
            - name: CLONE_GOOGLE_APPLICATION_CREDENTIALS
              value: "/etc/credentials/{{ .Values.restore.method.wal_g.gcloudCredentials }}"
            - name: USE_WALG_RESTORE
              value: "true"
            - name: CLONE_USE_WALG
              value: "true"
            {{ else if eq .Values.restore.method.name "wal-e" }}
            - name: CLONE_GOOGLE_APPLICATION_CREDENTIALS
              value: "/etc/credentials/{{ .Values.restore.method.wal_e.gcloudCredentials }}"
            {{ end }}
            {{ end }}
          ports:
            - containerPort: 8008
              name: patroni
              protocol: TCP
            - containerPort: 5432
              name: postgresql
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: datadir
              mountPath: /home/postgres/pgdata
            - name: patroni-config
              mountPath: /etc/patronictl
            {{ if .Values.gcloudCredentials.enabled }}
            - name: {{ .Values.gcloudCredentials.secretName }}
              mountPath: /etc/credentials
              readOnly: true
            {{ end }}
      volumes:
        {{ if .Values.gcloudCredentials.enabled }}
        - name: {{ .Values.gcloudCredentials.secretName }}
          secret:
            secretName: {{ .Values.gcloudCredentials.secretName }}
        {{ end }}
        - name: patroni-config
          configMap:
            name: {{ template "patroni.fullname" . }}-configmap
      {{- if .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      {{ end }}
      {{- if eq .Values.podAntiAffinity "hard" }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: "kubernetes.io/hostname"
              labelSelector:
                matchLabels:
                  app: "{{ template "patroni.name" . }}"
                  release: "{{ .Release.Name }}"
      {{- else if eq .Values.podAntiAffinity "soft" }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchLabels:
                    app: "{{ template "patroni.name" . }}"
                    release: "{{ .Release.Name }}"
      {{- end }}
  {{ if .Values.persistentVolume.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: datadir
      {{- if .Values.persistentVolume.annotations }}
        annotations:
          {{- toYaml .Values.persistentVolume.annotations | nindent 10 }}
      {{- end }}
      spec:
        accessModes:
        {{- range .Values.persistentVolume.accessModes }}
          - {{ . | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.persistentVolume.size | quote }}
        {{- if .Values.persistentVolume.storageClass }}
        {{- if (eq "-" .Values.persistentVolume.storageClass) }}
        storageClassName: ""
        {{- else }}
        storageClassName: "{{ .Values.persistentVolume.storageClass }}"
        {{- end }}
        {{- end }}
        {{- else }}
        - name: datadir
          emptyDir: {}
{{- end }}
