apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bitcore-role-binding
  namespace: bitcore-service
subjects:
  - kind: ServiceAccount
    name: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: bitcore-role

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: bitcore-role
rules:
  - apiGroups: [""]
    resources:
      - pods
      - nodes
    verbs:
      - get
      - list