# Default values for rehive-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
deployment:
  replicaCount: 3
  resources: {}
  command:
image:
  repository: rehive/example
  tag: latest
  pullPolicy: IfNotPresent
service:
  name: nginx
  type: ClusterIP
  externalPort: 80
  internalPort: 8000
  readinessProbe:
  livenessProbe:
envFromSecret:
  enabled: true
management:
  enabled: true
ingress:
  enabled: true
  hosts:
    - example.services.rehive.io
  annotations:
    kubernetes.io/ingress.class: "nginx"
    kubernetes.io/tls-acme: "true"
  tls:
    - hosts:
      - example.services.rehive.io
      secretName: stellar-service-tls
postgres:
  enabled: false
  host: patroni-example-patroni.example-namespace.svc.cluster.local
  user: admin
  port: 5432
  secret:
    name: patroni-example-patroni
    key: password-admin
redis:
  enabled: false
  host: redis-example-redis.example-namespace.svc.cluster.local
  port: 6379
  secret:
    name: redis-example-redis
    key: rabbitmq-password
rabbitmq:
  enabled: false
  host: patroni-example-patroni.example-namespace.svc.cluster.local
  port: 5672
  secret:
    name: rabbitmq-example-rabbitmq-ha
    key: rabbitmq-password
gcloudCredentials:
  enabled: false
  kubernetesSecret: gcloud_credentials
workersEnabled: false
workers:
  - name: worker-receive
    internalPort: 8000
    replicaCount: 1
    command: ['/bin/sh','-c', 'celery -A config.celery worker --loglevel=INFO --concurrency=1 -Q general-example']
    requests: {}
